I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 48, in script
    white "Go say hi to someone."
Exception: Sayer 'white' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 48, in script
    white "Go say hi to someone."
  File "C:\Users\minha\OneDrive\Desktop\renpy-8.2.3-sdk\renpy\ast.py", line 2560, in execute
    Say.execute(self)
  File "C:\Users\minha\OneDrive\Desktop\renpy-8.2.3-sdk\renpy\ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\minha\OneDrive\Desktop\renpy-8.2.3-sdk\renpy\ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'white' is not defined.

Windows-10-10.0.22631 AMD64
Ren'Py 8.2.3.24061702
ColoUrs 1.0
Sun Dec  8 21:34:39 2024
